version: '3'
services:
  app:
    container_name: node-app01
    restart: always
    build: .
    # default image name: master_app
    image: spcity/node-app01:latest
    volumes:
      # for aws (has /etc/letsencrypt)
      - /etc/letsencrypt:/etc/letsencrypt
      # Developement
      - ./app:/usr/src/app
      
      # for local (no /etc/letsencrypt)
      # - ./letsencrypt:/usr/src/app/letsencrypt
    ports:
      - '4000:3000'
      - '8443:443'
  #   links:
  #     - mongo
  #   depends_on:
  #     - mongo
  # mongo:
  #   container_name: mongo
  #   image: mongo:4
  #   volumes:
  #     - ./data:/data/db
  #   ports:
  #     - '27017:27017'